---
- name: Install nginx
  yum: name=nginx state=present

#- name: Ensure SELinux doesn't block Nginx
#  seboolean: name=httpd_can_network_connect state=yes persistent=yes

- name: Copy main nginx configuration
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Copy site nginx configuration
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify:
    - restart nginx
