relationships:
    - None: None

fields:
    - id: title
      label: Title
      field_class: CharField
      widget: TextInput
      required: True
      form_field: True

    - id: investigation type
      label: Investigation Type
      field_class: ChoiceField
      widget: Select
      choices:
          - Genomic
          - Imaging-Genetics
      required: True
      form_field: True

    - id: description
      label: Description
      field_class: CharField
      widget: Textarea
      required: False
      form_field: True

    - id: creator
      label: Creator
      form_field: False
