fields:
    - key: investigation type
      type: list
      options:
          - Genomic
    - key: title
      type: text
    - key: creator
      type: text
    - key: description
      type: text_long
